version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8080"

  wallet-service:
    build: ./wallet-service
    ports:
      - "8002:8080"

  transaction-service:
    build: ./transaction-service
    ports:
      - "8003:8080"

  notification-service:
    build: ./notification-service
    ports:
      - "8004:8080"
